//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("CiteUModel", "FK__Chambres__ID_Bat__398D8EEE", "Batiments", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CiteU.Modele.Batiments), "Chambres", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CiteU.Modele.Chambres), true)]
[assembly: EdmRelationshipAttribute("CiteUModel", "FK_ChambresLits", "Chambres", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CiteU.Modele.Chambres), "Lits", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CiteU.Modele.Lits), true)]
[assembly: EdmRelationshipAttribute("CiteUModel", "FK_ReservationsLits", "Lits", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CiteU.Modele.Lits), "Reservations", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CiteU.Modele.Reservations), true)]

#endregion

namespace CiteU.Modele
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class CiteUEntities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet CiteUEntities à l'aide de la chaîne de connexion trouvée dans la section 'CiteUEntities' du fichier de configuration d'application.
        /// </summary>
        public CiteUEntities() : base("name=CiteUEntities", "CiteUEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet CiteUEntities.
        /// </summary>
        public CiteUEntities(string connectionString) : base(connectionString, "CiteUEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet CiteUEntities.
        /// </summary>
        public CiteUEntities(EntityConnection connection) : base(connection, "CiteUEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Batiments> Batiments
        {
            get
            {
                if ((_Batiments == null))
                {
                    _Batiments = base.CreateObjectSet<Batiments>("Batiments");
                }
                return _Batiments;
            }
        }
        private ObjectSet<Batiments> _Batiments;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Chambres> Chambres
        {
            get
            {
                if ((_Chambres == null))
                {
                    _Chambres = base.CreateObjectSet<Chambres>("Chambres");
                }
                return _Chambres;
            }
        }
        private ObjectSet<Chambres> _Chambres;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Etudiants> Etudiants
        {
            get
            {
                if ((_Etudiants == null))
                {
                    _Etudiants = base.CreateObjectSet<Etudiants>("Etudiants");
                }
                return _Etudiants;
            }
        }
        private ObjectSet<Etudiants> _Etudiants;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Lits> Lits
        {
            get
            {
                if ((_Lits == null))
                {
                    _Lits = base.CreateObjectSet<Lits>("Lits");
                }
                return _Lits;
            }
        }
        private ObjectSet<Lits> _Lits;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Reservations> Reservations
        {
            get
            {
                if ((_Reservations == null))
                {
                    _Reservations = base.CreateObjectSet<Reservations>("Reservations");
                }
                return _Reservations;
            }
        }
        private ObjectSet<Reservations> _Reservations;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Batiments. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToBatiments(Batiments batiments)
        {
            base.AddObject("Batiments", batiments);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Chambres. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToChambres(Chambres chambres)
        {
            base.AddObject("Chambres", chambres);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Etudiants. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToEtudiants(Etudiants etudiants)
        {
            base.AddObject("Etudiants", etudiants);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Lits. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToLits(Lits lits)
        {
            base.AddObject("Lits", lits);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Reservations. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToReservations(Reservations reservations)
        {
            base.AddObject("Reservations", reservations);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CiteUModel", Name="Batiments")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Batiments : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Batiments.
        /// </summary>
        /// <param name="iD_Batiment">Valeur initiale de la propriété ID_Batiment.</param>
        public static Batiments CreateBatiments(global::System.Int32 iD_Batiment)
        {
            Batiments batiments = new Batiments();
            batiments.ID_Batiment = iD_Batiment;
            return batiments;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Batiment
        {
            get
            {
                return _ID_Batiment;
            }
            set
            {
                if (_ID_Batiment != value)
                {
                    OnID_BatimentChanging(value);
                    ReportPropertyChanging("ID_Batiment");
                    _ID_Batiment = StructuralObject.SetValidValue(value, "ID_Batiment");
                    ReportPropertyChanged("ID_Batiment");
                    OnID_BatimentChanged();
                }
            }
        }
        private global::System.Int32 _ID_Batiment;
        partial void OnID_BatimentChanging(global::System.Int32 value);
        partial void OnID_BatimentChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nom_Batiment
        {
            get
            {
                return _Nom_Batiment;
            }
            set
            {
                OnNom_BatimentChanging(value);
                ReportPropertyChanging("Nom_Batiment");
                _Nom_Batiment = StructuralObject.SetValidValue(value, true, "Nom_Batiment");
                ReportPropertyChanged("Nom_Batiment");
                OnNom_BatimentChanged();
            }
        }
        private global::System.String _Nom_Batiment;
        partial void OnNom_BatimentChanging(global::System.String value);
        partial void OnNom_BatimentChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Adresse_Batiment
        {
            get
            {
                return _Adresse_Batiment;
            }
            set
            {
                OnAdresse_BatimentChanging(value);
                ReportPropertyChanging("Adresse_Batiment");
                _Adresse_Batiment = StructuralObject.SetValidValue(value, true, "Adresse_Batiment");
                ReportPropertyChanged("Adresse_Batiment");
                OnAdresse_BatimentChanged();
            }
        }
        private global::System.String _Adresse_Batiment;
        partial void OnAdresse_BatimentChanging(global::System.String value);
        partial void OnAdresse_BatimentChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description_Batiment
        {
            get
            {
                return _Description_Batiment;
            }
            set
            {
                OnDescription_BatimentChanging(value);
                ReportPropertyChanging("Description_Batiment");
                _Description_Batiment = StructuralObject.SetValidValue(value, true, "Description_Batiment");
                ReportPropertyChanged("Description_Batiment");
                OnDescription_BatimentChanged();
            }
        }
        private global::System.String _Description_Batiment;
        partial void OnDescription_BatimentChanging(global::System.String value);
        partial void OnDescription_BatimentChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Nombre_Etages
        {
            get
            {
                return _Nombre_Etages;
            }
            set
            {
                OnNombre_EtagesChanging(value);
                ReportPropertyChanging("Nombre_Etages");
                _Nombre_Etages = StructuralObject.SetValidValue(value, "Nombre_Etages");
                ReportPropertyChanged("Nombre_Etages");
                OnNombre_EtagesChanged();
            }
        }
        private Nullable<global::System.Int32> _Nombre_Etages;
        partial void OnNombre_EtagesChanging(Nullable<global::System.Int32> value);
        partial void OnNombre_EtagesChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Nombre_max_chambre
        {
            get
            {
                return _Nombre_max_chambre;
            }
            set
            {
                OnNombre_max_chambreChanging(value);
                ReportPropertyChanging("Nombre_max_chambre");
                _Nombre_max_chambre = StructuralObject.SetValidValue(value, "Nombre_max_chambre");
                ReportPropertyChanged("Nombre_max_chambre");
                OnNombre_max_chambreChanged();
            }
        }
        private Nullable<global::System.Int32> _Nombre_max_chambre;
        partial void OnNombre_max_chambreChanging(Nullable<global::System.Int32> value);
        partial void OnNombre_max_chambreChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CiteUModel", "FK__Chambres__ID_Bat__398D8EEE", "Chambres")]
        public EntityCollection<Chambres> Chambres
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Chambres>("CiteUModel.FK__Chambres__ID_Bat__398D8EEE", "Chambres");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Chambres>("CiteUModel.FK__Chambres__ID_Bat__398D8EEE", "Chambres", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CiteUModel", Name="Chambres")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Chambres : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Chambres.
        /// </summary>
        /// <param name="iD_Chambre">Valeur initiale de la propriété ID_Chambre.</param>
        /// <param name="numero_Chambre">Valeur initiale de la propriété Numero_Chambre.</param>
        public static Chambres CreateChambres(global::System.Int32 iD_Chambre, global::System.Int32 numero_Chambre)
        {
            Chambres chambres = new Chambres();
            chambres.ID_Chambre = iD_Chambre;
            chambres.Numero_Chambre = numero_Chambre;
            return chambres;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Chambre
        {
            get
            {
                return _ID_Chambre;
            }
            set
            {
                if (_ID_Chambre != value)
                {
                    OnID_ChambreChanging(value);
                    ReportPropertyChanging("ID_Chambre");
                    _ID_Chambre = StructuralObject.SetValidValue(value, "ID_Chambre");
                    ReportPropertyChanged("ID_Chambre");
                    OnID_ChambreChanged();
                }
            }
        }
        private global::System.Int32 _ID_Chambre;
        partial void OnID_ChambreChanging(global::System.Int32 value);
        partial void OnID_ChambreChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_Batiment
        {
            get
            {
                return _ID_Batiment;
            }
            set
            {
                OnID_BatimentChanging(value);
                ReportPropertyChanging("ID_Batiment");
                _ID_Batiment = StructuralObject.SetValidValue(value, "ID_Batiment");
                ReportPropertyChanged("ID_Batiment");
                OnID_BatimentChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_Batiment;
        partial void OnID_BatimentChanging(Nullable<global::System.Int32> value);
        partial void OnID_BatimentChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nom_Chambre
        {
            get
            {
                return _Nom_Chambre;
            }
            set
            {
                OnNom_ChambreChanging(value);
                ReportPropertyChanging("Nom_Chambre");
                _Nom_Chambre = StructuralObject.SetValidValue(value, true, "Nom_Chambre");
                ReportPropertyChanged("Nom_Chambre");
                OnNom_ChambreChanged();
            }
        }
        private global::System.String _Nom_Chambre;
        partial void OnNom_ChambreChanging(global::System.String value);
        partial void OnNom_ChambreChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Numero_Batiment
        {
            get
            {
                return _Numero_Batiment;
            }
            set
            {
                OnNumero_BatimentChanging(value);
                ReportPropertyChanging("Numero_Batiment");
                _Numero_Batiment = StructuralObject.SetValidValue(value, "Numero_Batiment");
                ReportPropertyChanged("Numero_Batiment");
                OnNumero_BatimentChanged();
            }
        }
        private Nullable<global::System.Int32> _Numero_Batiment;
        partial void OnNumero_BatimentChanging(Nullable<global::System.Int32> value);
        partial void OnNumero_BatimentChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Capacite
        {
            get
            {
                return _Capacite;
            }
            set
            {
                OnCapaciteChanging(value);
                ReportPropertyChanging("Capacite");
                _Capacite = StructuralObject.SetValidValue(value, "Capacite");
                ReportPropertyChanged("Capacite");
                OnCapaciteChanged();
            }
        }
        private Nullable<global::System.Int32> _Capacite;
        partial void OnCapaciteChanging(Nullable<global::System.Int32> value);
        partial void OnCapaciteChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Etage
        {
            get
            {
                return _Etage;
            }
            set
            {
                OnEtageChanging(value);
                ReportPropertyChanging("Etage");
                _Etage = StructuralObject.SetValidValue(value, "Etage");
                ReportPropertyChanged("Etage");
                OnEtageChanged();
            }
        }
        private Nullable<global::System.Int32> _Etage;
        partial void OnEtageChanging(Nullable<global::System.Int32> value);
        partial void OnEtageChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Statut
        {
            get
            {
                return _Statut;
            }
            set
            {
                OnStatutChanging(value);
                ReportPropertyChanging("Statut");
                _Statut = StructuralObject.SetValidValue(value, true, "Statut");
                ReportPropertyChanged("Statut");
                OnStatutChanged();
            }
        }
        private global::System.String _Statut;
        partial void OnStatutChanging(global::System.String value);
        partial void OnStatutChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Numero_Chambre
        {
            get
            {
                return _Numero_Chambre;
            }
            set
            {
                OnNumero_ChambreChanging(value);
                ReportPropertyChanging("Numero_Chambre");
                _Numero_Chambre = StructuralObject.SetValidValue(value, "Numero_Chambre");
                ReportPropertyChanged("Numero_Chambre");
                OnNumero_ChambreChanged();
            }
        }
        private global::System.Int32 _Numero_Chambre;
        partial void OnNumero_ChambreChanging(global::System.Int32 value);
        partial void OnNumero_ChambreChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CiteUModel", "FK__Chambres__ID_Bat__398D8EEE", "Batiments")]
        public Batiments Batiments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Batiments>("CiteUModel.FK__Chambres__ID_Bat__398D8EEE", "Batiments").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Batiments>("CiteUModel.FK__Chambres__ID_Bat__398D8EEE", "Batiments").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Batiments> BatimentsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Batiments>("CiteUModel.FK__Chambres__ID_Bat__398D8EEE", "Batiments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Batiments>("CiteUModel.FK__Chambres__ID_Bat__398D8EEE", "Batiments", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CiteUModel", "FK_ChambresLits", "Lits")]
        public EntityCollection<Lits> Lits
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Lits>("CiteUModel.FK_ChambresLits", "Lits");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Lits>("CiteUModel.FK_ChambresLits", "Lits", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CiteUModel", Name="Etudiants")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Etudiants : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Etudiants.
        /// </summary>
        /// <param name="iD_Etudiant">Valeur initiale de la propriété ID_Etudiant.</param>
        public static Etudiants CreateEtudiants(global::System.Int32 iD_Etudiant)
        {
            Etudiants etudiants = new Etudiants();
            etudiants.ID_Etudiant = iD_Etudiant;
            return etudiants;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Etudiant
        {
            get
            {
                return _ID_Etudiant;
            }
            set
            {
                if (_ID_Etudiant != value)
                {
                    OnID_EtudiantChanging(value);
                    ReportPropertyChanging("ID_Etudiant");
                    _ID_Etudiant = StructuralObject.SetValidValue(value, "ID_Etudiant");
                    ReportPropertyChanged("ID_Etudiant");
                    OnID_EtudiantChanged();
                }
            }
        }
        private global::System.Int32 _ID_Etudiant;
        partial void OnID_EtudiantChanging(global::System.Int32 value);
        partial void OnID_EtudiantChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, true, "Nom");
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prenom
        {
            get
            {
                return _Prenom;
            }
            set
            {
                OnPrenomChanging(value);
                ReportPropertyChanging("Prenom");
                _Prenom = StructuralObject.SetValidValue(value, true, "Prenom");
                ReportPropertyChanged("Prenom");
                OnPrenomChanged();
            }
        }
        private global::System.String _Prenom;
        partial void OnPrenomChanging(global::System.String value);
        partial void OnPrenomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date_Naissance
        {
            get
            {
                return _Date_Naissance;
            }
            set
            {
                OnDate_NaissanceChanging(value);
                ReportPropertyChanging("Date_Naissance");
                _Date_Naissance = StructuralObject.SetValidValue(value, "Date_Naissance");
                ReportPropertyChanged("Date_Naissance");
                OnDate_NaissanceChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date_Naissance;
        partial void OnDate_NaissanceChanging(Nullable<global::System.DateTime> value);
        partial void OnDate_NaissanceChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sexe
        {
            get
            {
                return _Sexe;
            }
            set
            {
                OnSexeChanging(value);
                ReportPropertyChanging("Sexe");
                _Sexe = StructuralObject.SetValidValue(value, true, "Sexe");
                ReportPropertyChanged("Sexe");
                OnSexeChanged();
            }
        }
        private global::System.String _Sexe;
        partial void OnSexeChanging(global::System.String value);
        partial void OnSexeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telephone
        {
            get
            {
                return _Telephone;
            }
            set
            {
                OnTelephoneChanging(value);
                ReportPropertyChanging("Telephone");
                _Telephone = StructuralObject.SetValidValue(value, true, "Telephone");
                ReportPropertyChanged("Telephone");
                OnTelephoneChanged();
            }
        }
        private global::System.String _Telephone;
        partial void OnTelephoneChanging(global::System.String value);
        partial void OnTelephoneChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Handicape
        {
            get
            {
                return _Handicape;
            }
            set
            {
                OnHandicapeChanging(value);
                ReportPropertyChanging("Handicape");
                _Handicape = StructuralObject.SetValidValue(value, "Handicape");
                ReportPropertyChanged("Handicape");
                OnHandicapeChanged();
            }
        }
        private Nullable<global::System.Int32> _Handicape;
        partial void OnHandicapeChanging(Nullable<global::System.Int32> value);
        partial void OnHandicapeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Reservations_ID_Reservation
        {
            get
            {
                return _Reservations_ID_Reservation;
            }
            set
            {
                OnReservations_ID_ReservationChanging(value);
                ReportPropertyChanging("Reservations_ID_Reservation");
                _Reservations_ID_Reservation = StructuralObject.SetValidValue(value, "Reservations_ID_Reservation");
                ReportPropertyChanged("Reservations_ID_Reservation");
                OnReservations_ID_ReservationChanged();
            }
        }
        private Nullable<global::System.Int32> _Reservations_ID_Reservation;
        partial void OnReservations_ID_ReservationChanging(Nullable<global::System.Int32> value);
        partial void OnReservations_ID_ReservationChanged();

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CiteUModel", Name="Lits")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Lits : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Lits.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        /// <param name="chambresID_Chambre">Valeur initiale de la propriété ChambresID_Chambre.</param>
        public static Lits CreateLits(global::System.Int32 id, global::System.Int32 chambresID_Chambre)
        {
            Lits lits = new Lits();
            lits.id = id;
            lits.ChambresID_Chambre = chambresID_Chambre;
            return lits;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ChambresID_Chambre
        {
            get
            {
                return _ChambresID_Chambre;
            }
            set
            {
                OnChambresID_ChambreChanging(value);
                ReportPropertyChanging("ChambresID_Chambre");
                _ChambresID_Chambre = StructuralObject.SetValidValue(value, "ChambresID_Chambre");
                ReportPropertyChanged("ChambresID_Chambre");
                OnChambresID_ChambreChanged();
            }
        }
        private global::System.Int32 _ChambresID_Chambre;
        partial void OnChambresID_ChambreChanging(global::System.Int32 value);
        partial void OnChambresID_ChambreChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Reservations_ID_Reservation
        {
            get
            {
                return _Reservations_ID_Reservation;
            }
            set
            {
                OnReservations_ID_ReservationChanging(value);
                ReportPropertyChanging("Reservations_ID_Reservation");
                _Reservations_ID_Reservation = StructuralObject.SetValidValue(value, "Reservations_ID_Reservation");
                ReportPropertyChanged("Reservations_ID_Reservation");
                OnReservations_ID_ReservationChanged();
            }
        }
        private Nullable<global::System.Int32> _Reservations_ID_Reservation;
        partial void OnReservations_ID_ReservationChanging(Nullable<global::System.Int32> value);
        partial void OnReservations_ID_ReservationChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CiteUModel", "FK_ChambresLits", "Chambres")]
        public Chambres Chambres
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Chambres>("CiteUModel.FK_ChambresLits", "Chambres").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Chambres>("CiteUModel.FK_ChambresLits", "Chambres").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Chambres> ChambresReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Chambres>("CiteUModel.FK_ChambresLits", "Chambres");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Chambres>("CiteUModel.FK_ChambresLits", "Chambres", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CiteUModel", "FK_ReservationsLits", "Reservations")]
        public EntityCollection<Reservations> Reservations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reservations>("CiteUModel.FK_ReservationsLits", "Reservations");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reservations>("CiteUModel.FK_ReservationsLits", "Reservations", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CiteUModel", Name="Reservations")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Reservations : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Reservations.
        /// </summary>
        /// <param name="iD_Reservation">Valeur initiale de la propriété ID_Reservation.</param>
        /// <param name="lits_id">Valeur initiale de la propriété Lits_id.</param>
        public static Reservations CreateReservations(global::System.Int32 iD_Reservation, global::System.Int32 lits_id)
        {
            Reservations reservations = new Reservations();
            reservations.ID_Reservation = iD_Reservation;
            reservations.Lits_id = lits_id;
            return reservations;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Reservation
        {
            get
            {
                return _ID_Reservation;
            }
            set
            {
                if (_ID_Reservation != value)
                {
                    OnID_ReservationChanging(value);
                    ReportPropertyChanging("ID_Reservation");
                    _ID_Reservation = StructuralObject.SetValidValue(value, "ID_Reservation");
                    ReportPropertyChanged("ID_Reservation");
                    OnID_ReservationChanged();
                }
            }
        }
        private global::System.Int32 _ID_Reservation;
        partial void OnID_ReservationChanging(global::System.Int32 value);
        partial void OnID_ReservationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_Etudiant
        {
            get
            {
                return _ID_Etudiant;
            }
            set
            {
                OnID_EtudiantChanging(value);
                ReportPropertyChanging("ID_Etudiant");
                _ID_Etudiant = StructuralObject.SetValidValue(value, "ID_Etudiant");
                ReportPropertyChanged("ID_Etudiant");
                OnID_EtudiantChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_Etudiant;
        partial void OnID_EtudiantChanging(Nullable<global::System.Int32> value);
        partial void OnID_EtudiantChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_Chambre
        {
            get
            {
                return _ID_Chambre;
            }
            set
            {
                OnID_ChambreChanging(value);
                ReportPropertyChanging("ID_Chambre");
                _ID_Chambre = StructuralObject.SetValidValue(value, "ID_Chambre");
                ReportPropertyChanged("ID_Chambre");
                OnID_ChambreChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_Chambre;
        partial void OnID_ChambreChanging(Nullable<global::System.Int32> value);
        partial void OnID_ChambreChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date_Debut
        {
            get
            {
                return _Date_Debut;
            }
            set
            {
                OnDate_DebutChanging(value);
                ReportPropertyChanging("Date_Debut");
                _Date_Debut = StructuralObject.SetValidValue(value, "Date_Debut");
                ReportPropertyChanged("Date_Debut");
                OnDate_DebutChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date_Debut;
        partial void OnDate_DebutChanging(Nullable<global::System.DateTime> value);
        partial void OnDate_DebutChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date_Fin
        {
            get
            {
                return _Date_Fin;
            }
            set
            {
                OnDate_FinChanging(value);
                ReportPropertyChanging("Date_Fin");
                _Date_Fin = StructuralObject.SetValidValue(value, "Date_Fin");
                ReportPropertyChanged("Date_Fin");
                OnDate_FinChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date_Fin;
        partial void OnDate_FinChanging(Nullable<global::System.DateTime> value);
        partial void OnDate_FinChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Statut_Paiement
        {
            get
            {
                return _Statut_Paiement;
            }
            set
            {
                OnStatut_PaiementChanging(value);
                ReportPropertyChanging("Statut_Paiement");
                _Statut_Paiement = StructuralObject.SetValidValue(value, true, "Statut_Paiement");
                ReportPropertyChanged("Statut_Paiement");
                OnStatut_PaiementChanged();
            }
        }
        private global::System.String _Statut_Paiement;
        partial void OnStatut_PaiementChanging(global::System.String value);
        partial void OnStatut_PaiementChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date_Payement
        {
            get
            {
                return _Date_Payement;
            }
            set
            {
                OnDate_PayementChanging(value);
                ReportPropertyChanging("Date_Payement");
                _Date_Payement = StructuralObject.SetValidValue(value, "Date_Payement");
                ReportPropertyChanged("Date_Payement");
                OnDate_PayementChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date_Payement;
        partial void OnDate_PayementChanging(Nullable<global::System.DateTime> value);
        partial void OnDate_PayementChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Lits_id
        {
            get
            {
                return _Lits_id;
            }
            set
            {
                OnLits_idChanging(value);
                ReportPropertyChanging("Lits_id");
                _Lits_id = StructuralObject.SetValidValue(value, "Lits_id");
                ReportPropertyChanged("Lits_id");
                OnLits_idChanged();
            }
        }
        private global::System.Int32 _Lits_id;
        partial void OnLits_idChanging(global::System.Int32 value);
        partial void OnLits_idChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CiteUModel", "FK_ReservationsLits", "Lits")]
        public Lits Lits
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Lits>("CiteUModel.FK_ReservationsLits", "Lits").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Lits>("CiteUModel.FK_ReservationsLits", "Lits").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Lits> LitsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Lits>("CiteUModel.FK_ReservationsLits", "Lits");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Lits>("CiteUModel.FK_ReservationsLits", "Lits", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
